name: Run Kaggle Notebook

on:
  workflow_dispatch:

jobs:
  run-kaggle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Download Kaggle API key
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Load notebook on Kaggle
        run: |
          cp notebooks/train_check.ipynb train_check.ipynb
          kaggle kernels push -p .

      - name: Start notebook
        run: |
          kaggle kernels list --user ${{ secrets.KAGGLE_USERNAME }} --sort-by dateCreated
          NOTEBOOK_ID=$(kaggle kernels list --user ${{ secrets.KAGGLE_USERNAME }} --sort-by dateCreated | grep train_check | head -n 1 | awk '{print $1}')
          kaggle kernels output $NOTEBOOK_ID --path output --wait