name: Run Python Script Manually or on Push

on:
  workflow_dispatch:  # GitHub UI
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install torch and torch-* from PyTorch index
        run: |
          pip install torch==2.2.0 \
            torch-scatter==2.1.2 \
            torch-sparse==0.6.18 \
            torch-geometric==2.6.1 \
            --index-url https://data.pyg.org/whl/torch-2.2.0+cpu.html

      - name: Install remaining requirements
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python src/scripts/checking.py
